BASE_URL = "https://qa-desk.education-services.ru"

MAIN_PAGE_ENDPOINT = "/"
CREATE_POST_ENDPOINT = "/create-lisiting"
PROFILE_ENDPOINT = "/profile"

MAIN_PAGE_URL = f"{BASE_URL}{MAIN_PAGE_ENDPOINT}"
CREATE_POST_URL = f"{BASE_URL}{CREATE_POST_ENDPOINT}"
PROFILE_URL = f"{BASE_URL}{PROFILE_ENDPOINT}"
